# bundle install vendor/bundler_gems --disable-shared-gems
source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'rails', '2.3.5'
gem 'haml'
gem 'friendly_id'
gem 'resource_controller'
gem 'mysql'
gem 'delayed_job'
gem 'rest-client'
gem 'grit'
gem 'git'
gem 'syntax'
gem 'hpricot'
gem 'morph'
gem 'whenever'
gem 'twfy'
gem 'fastercsv'
gem 'pdf-reader'
gem 'cmess'
gem 'google-translate'
# gem 'mechanize'

group :test do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'test-unit', '1.2.3'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'webrat'
  gem 'autotest-rails'
end